# -*- mode: ruby -*-
# vi: set ft=ruby :

require "~/chef/box"
Box.new "medlink",
  recipes: "jdabbs",
  json: {
    projects: {
      medlink: {
        user:       "james",
        repository: "git://github.com/atlrug-rhok/medlink.git"
      }
    }
  }

