# -*- mode: ruby -*-
# vi: set ft=ruby :

ROOT = "~/chef"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-server-10044-x64-vbox4210-nocm.box"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box"

  # See also :public_network and forwarded port mapping options
  config.vm.network :private_network, ip: "33.33.33.10"

  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "#{ROOT}/Berksfile"

  config.vm.hostname = "base"
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "#{ROOT}"
    chef.data_bags_path = "#{ROOT}/data_bags"

    chef.json = {}

    chef.run_list = [
      "recipe[chef-solo-search::default]",
      "recipe[jdabbs::default]"
    ]
  end
end

